src/Entity/VinylMix.php
<?php

namespace App\Entity;

use App\Repository\VinylMixRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use Gedmo\Timestampable\Traits\TimestampableEntity;

#[ORM\Entity(repositoryClass: VinylMixRepository::class)]
class VinylMix
{
    use TimestampableEntity;

//    public function __construct()
//    {
//        $this->createdAt = new \DateTimeImmutable();
//    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column]
    private ?int $trackCount = null;

//    #[ORM\Column]
//    private \DateTimeImmutable $createdAt;

    #[ORM\Column]
    private int $votes = 0;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getTrackCount(): ?int
    {
        return $this->trackCount;
    }

    public function setTrackCount(int $trackCount): static
    {
        $this->trackCount = $trackCount;

        return $this;
    }

//    public function getCreatedAt(): ?\DateTimeImmutable
//    {
//        return $this->createdAt;
//    }
//
//    public function setCreatedAt(\DateTimeImmutable $createdAt): static
//    {
//        $this->createdAt = $createdAt;
//
//        return $this;
//    }

    public function getVotes(): ?int
    {
        return $this->votes;
    }

    public function setVotes(int $votes): static
    {
        $this->votes = $votes;

        return $this;
    }

    public function upVote()
    {
        $this->votes++;
    }

    public function downVote()
    {
        $this->votes--;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getVotesString(): string
    {
        $prefix = ($this->votes > 0 ? '+' : '-');
        return sprintf('%s %d', $prefix, abs($this->votes));
    }

    public function getImageUrl(int $width): string
    {
        return sprintf(
            'https://picsum.photos/id/%d/%d',
            ($this->getId() + 50) % 1000, // number between 0 and 1000, based on the id
            $width
        );
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }


}

src/Controller/MixController.php
<?php

namespace App\Controller;

use App\Entity\VinylMix;
use App\Repository\VinylMixRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class MixController extends AbstractController
{

    public function __construct(
        private VinylMixRepository     $VinylMixRepository,
        private EntityManagerInterface $entityManager
    )
    {
    }

    #[Route('mix/new')]
    public function new(EntityManagerInterface $entityManager): Response
    {


        return new Response(sprintf(
            'Mix %d is %d tracks of pure 80 heaven',
            $mix->getId(),
            $mix->gettrackCount()
        ));
    }

    #[Route('/mix/{slug}', name: 'app_mix_show')]
    public function show(VinylMix $mix):Response
    {
        //Esto no es necesario si pasamos como argumento VinylMix, es util cuando necesitamos un simple objeto, siempre
        //que el wildcard coincida con lo que hay en la bd, en este caso id
//        $mix = $this->VinylMixRepository->find($id);
//
//        if(!$mix){
//            throw $this->createNotFoundException('Mix not found');
//        }


        return $this->render('mix/show.html.twig', [
            'mix' => $mix
        ]);
    }


    #[Route('mix/{id}/vote', name: 'app_mix_vote', methods: ['POST'])]
    public function vote(VinylMix $mix, Request $request): Response
    {
        $miReq = $request;
//        dd($miReq);

        $direction = $request->request->get('direction', 'up');
        if ($direction == 'up') {
            $mix->upVote();
        } else {
            $mix->downVote();
        }
        $this->entityManager->flush(); //Doctrine guarda los objetos
        $this->addFlash('success','Vote counted');
        return $this->redirectToRoute('app_mix_show', ['slug' => $mix->getSlug()]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class SongController extends AbstractController
{
    #[Route('/api/songs/{id<\d+>}', methods: ['GET'], name: 'api_songs_get_one')]
    public function getSong(int $id, LoggerInterface $logger): Response
    {
        // TODO query the database
        $song = [
            'id' => $id,
            'name' => 'Waterfalls',
            'url' => 'https://symfonycasts.s3.amazonaws.com/sample.mp3',
        ];

        $logger->info('Returning API response for song {song}', [
            'song' => $id,
        ]);

//        return new JsonResponse(($song));
        return $this->json($song);
    }

}

src/Controller/VinylController.php
<?php

namespace App\Controller;

use App\Entity\VinylMix;
use App\Repository\VinylMixRepository;
use App\Service\MixRepository;
use Doctrine\ORM\EntityManagerInterface;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use function Symfony\Component\String\u;

class VinylController extends AbstractController
{

    public function __construct(
        private bool                   $isDebug,
        private MixRepository          $mixRepository,
        private EntityManagerInterface $entityManager,
        private VinylMixRepository     $VinylMixRepository,

    )
    {
    }

    #[Route('/', name: 'app_homepage')]
    public function homepage(): Response
    {
        $tracks = [
            ['song' => 'Gangsta\'s Paradise', 'artist' => 'Coolio'],
            ['song' => 'Waterfalls', 'artist' => 'TLC'],
            ['song' => 'Creep', 'artist' => 'Radiohead'],
            ['song' => 'Kiss from a Rose', 'artist' => 'Seal'],
            ['song' => 'On Bended Knee', 'artist' => 'Boyz II Men'],
            ['song' => 'Fantasy', 'artist' => 'Mariah Carey'],
        ];

        return $this->render('vinyl/homepage.html.twig', [
            'title' => 'PB & Jams',
            'tracks' => $tracks,
        ]);
    }

    #[Route('/browse/{slug}', name: 'app_browse')]
    public function browse(Request $request, ?string $slug = null): Response
    {
        $genre = $slug ? u(str_replace('-', ' ', $slug))->title(true) : null;

        //EntityManagerInterface
//        $mixRepository = $this->entityManager->getRepository(VinylMix::class);
//        $mixes = $mixRepository->findAll();
//        $mixes = $this->mixRepository->findAll();

        //VinylMixRepository como Servicio
//        $mixes = $this->VinylMixRepository->findAll();
//        $mixes = $this->VinylMixRepository->findAllOrderedByVotes($slug);


        //En vez de mostrar todos, vamos a meter paginization con pagerfanta bundle
        $queryBuilder = $this->VinylMixRepository->createOrderedByVotesQueryBuilder($slug);
        $adapter = new QueryAdapter($queryBuilder);
        $pagerfanta = Pagerfanta::createForCurrentPageWithMaxPerPage(
            $adapter,
            $request->query->getInt('page', 1),
            9
        );

//        dd($pagerfanta);
        return $this->render('vinyl/browse.html.twig', [
            'genre' => $genre,
            'pagerfanta' => $pagerfanta,
//            'mixes' => $mixes
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Mixed Vinyl{% endblock %}</title>

    <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon-16x16.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon-32x32.png') }}">

    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>

<!-- Main Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark  mb-5" style="background-color: #27333A;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path('app_homepage') }}">
            <i class="fas fa-record-vinyl"></i>
            Mixed Vinyl
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" style="margin-top: 20px;" href="{{ path('app_browse') }}">Browse Mixes</a>
                </li>
                <!-- Not Authenticated -->
                <!-- <li class="nav-item"><button href="#" class="btn btn-primary btn-sm">Login</button></li> -->
                <!-- End Not Authenticated -->

                <!-- If Authenticated -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-user-astronaut p-2"
                           style="border: solid 1px #fff; border-radius: 50px; font-size: 40px;"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="#">My Mixes</a></li>
                        <li><a class="dropdown-item" href="#">Signout</a></li>
                    </ul>
                </li>
                <!-- End If Authenticated -->
            </ul>
        </div>
    </div>
</nav>
<!-- End Main Navigation -->


{% for message in app.flashes('success') %}
    <div class="alert alert-success">
        {{ message }}
    </div>

{% endfor %}

{% block body %}{% endblock %}

<!-- Footer -->
<div class="container mt-5">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <span class="me-1" style="color: red;"><i class="fas fa-heart"></i></span>
            <span class="text-muted me-1">The guys and gals at</span>
            <a target="_blank" href="https://symfonycasts.com/" style="color: #25a1dd"
               class="mb-3 me-2 mb-md-0 text-decoration-none lh-1">
                SymfonyCasts
            </a>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" target="_blank" href="https://github.com/SymfonyCasts/symfony6"><i
                            class="fab fa-github"></i></a></li>
        </ul>
    </footer>
</div>
<!-- End Footer -->

</body>
</html>

templates/mix/_recordSvg.html.twig
<svg width="100%" height="100%" viewBox="0 0 496 496" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#C380F3" offset="0%"></stop>
            <stop stop-color="#4A90E2" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="Mixed-Vinyl" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="Group">
            <g id="record-vinyl" fill="#000000" fill-rule="nonzero">
                <path d="M248,144 C190.562386,144 144,190.562386 144,248 C144,305.437614 190.562386,352 248,352 C305.437614,352 352,305.437614 352,248 C352,190.562386 305.437614,144 248,144 L248,144 Z M248,272 C234.745166,272 224,261.254834 224,248 C224,234.745166 234.745166,224 248,224 C261.254834,224 272,234.745166 272,248 C272,261.254834 261.254834,272 248,272 Z M248,0 C111,0 0,111 0,248 C0,385 111,496 248,496 C385,496 496,385 496,248 C496,111 385,0 248,0 Z M248,376 C177.307552,376 120,318.692448 120,248 C120,177.307552 177.307552,120 248,120 C318.692448,120 376,177.307552 376,248 C376,281.947711 362.514324,314.505012 338.509668,338.509668 C314.505012,362.514324 281.947711,376 248,376 Z" id="Shape"></path>
            </g>
            <g id="record-vinyl" transform="translate(144.000000, 144.000000)" fill="url(#linearGradient-1)" fill-rule="nonzero">
                <path d="M104,0 C46.562386,0 0,46.562386 0,104 C0,161.437614 46.562386,208 104,208 C161.437614,208 208,161.437614 208,104 C208,46.562386 161.437614,0 104,0 L104,0 Z M104,128 C90.745166,128 80,117.254834 80,104 C80,90.745166 90.745166,80 104,80 C117.254834,80 128,90.745166 128,104 C128,117.254834 117.254834,128 104,128 Z" id="Shape"></path>
            </g>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="235"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="215"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="195"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="175"></circle>
            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="155"></circle>
        </g>
    </g>
</svg>

templates/mix/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ mix.title }} Mix{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="d-inline me-3">{{ mix.title }}</h1>
        <div class="row mt-5">
            <div class="col-12 col-md-4">
                {{ include('mix/_recordSvg.html.twig') }}
            </div>
            <div class="col-12 col-md-8 ps-5">
                <h2 class="mb-4">{{ mix.trackCount }} songs <small>(genre: {{ mix.genre }})</small></h2>
                <p>{{ mix.description }}</p>

                {{ mix.votesString }} votes
                <form action="{{ path('app_mix_vote', {id: mix.id }) }}" method="POST">
                    <button
                            type="submit"
                            class="btn btn-outline-primary"
                            name="direction"
                            value="up"
                    ><span class="fa fa-thumbs-up"></span></button>
                    <button
                            type="submit"
                            class="btn btn-outline-primary"
                            name="direction"
                            value="down"
                    ><span class="fa fa-thumbs-down"></span></button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/vinyl/browse.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Browse {{ genre ? genre : 'All Genres' }}</h1>

        <h2 class="mt-5 mb-4">Filter by Genre</h2>
        <ul class="genre-list ps-0 mt-2 mb-3">
            <li class="d-inline">
                <a class="btn btn-primary btn-sm" href="{{ path('app_browse', {
                    slug: 'pop'
                }) }}">Pop</a>
            </li>
            <li class="d-inline">
                <a class="btn btn-primary btn-sm" href="{{ path('app_browse', {
                    slug: 'rock'
                }) }}">Rock</a>
            </li>
            <li class="d-inline">
                <a class="btn btn-primary btn-sm" href="{{ path('app_browse', {
                    slug: 'heavy-metal'
                }) }}">Heavy Metal</a>
            </li>
        </ul>

        <div>
            <h2 class="mt-5">Mixes</h2>
            <turbo-frame id="mix-browse-list-{{ pagerfanta.currentPage }}" target="_top">
                <div class="row">
                    {% for mix in pagerfanta %}
                        <a
                                href="{{ path('app_mix_show', {
                                    slug:mix.slug
                                }) }}"
                                class="col col-md-4">
                            <div class="mixed-vinyl-container p-3 text-center">
                                <img src="{{ mix.imageUrl(300) }}" alt="Mix album cover">
                                <p class="mt-2"><strong>{{ mix.title }}</strong></p>
                                <span>{{ mix.trackCount }} Tracks</span>
                                |
                                <span>{{ mix.genre }}</span>
                                |
                                <span>{{ mix.createdAt | ago }}</span>
                                <br>
                                {{ mix.votesString }} votes
                            </div>
                        </a>
                    {% endfor %}

                    {% if pagerfanta.hasNextPage %}
                        <turbo-frame id="mix-browse-list-{{ pagerfanta.nextPage }}"
                                     src="{{ pagerfanta_page_url(pagerfanta, pagerfanta.nextPage) }}" loading="lazy"
                                     target="_top"></turbo-frame>
                    {% endif %}
                </div>
            </turbo-frame>
        </div>
    </div>
{% endblock %}

templates/vinyl/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Create a new Record | {{ parent() }}{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="d-inline me-3">{{ title }}</h1> <i class="fas fa-edit"></i>
        <div class="row mt-5">
            <div class="col-12 col-md-4">

                <svg width="100%" height="100%" viewBox="0 0 496 496" xmlns="http://www.w3.org/2000/svg"
                     xmlns:xlink="http://www.w3.org/1999/xlink">
                    <defs>
                        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
                            <stop stop-color="#C380F3" offset="0%"></stop>
                            <stop stop-color="#4A90E2" offset="100%"></stop>
                        </linearGradient>
                    </defs>
                    <g id="Mixed-Vinyl" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <g id="Group">
                            <g id="record-vinyl" fill="#000000" fill-rule="nonzero">
                                <path d="M248,144 C190.562386,144 144,190.562386 144,248 C144,305.437614 190.562386,352 248,352 C305.437614,352 352,305.437614 352,248 C352,190.562386 305.437614,144 248,144 L248,144 Z M248,272 C234.745166,272 224,261.254834 224,248 C224,234.745166 234.745166,224 248,224 C261.254834,224 272,234.745166 272,248 C272,261.254834 261.254834,272 248,272 Z M248,0 C111,0 0,111 0,248 C0,385 111,496 248,496 C385,496 496,385 496,248 C496,111 385,0 248,0 Z M248,376 C177.307552,376 120,318.692448 120,248 C120,177.307552 177.307552,120 248,120 C318.692448,120 376,177.307552 376,248 C376,281.947711 362.514324,314.505012 338.509668,338.509668 C314.505012,362.514324 281.947711,376 248,376 Z"
                                      id="Shape"></path>
                            </g>
                            <g id="record-vinyl" transform="translate(144.000000, 144.000000)"
                               fill="url(#linearGradient-1)" fill-rule="nonzero">
                                <path d="M104,0 C46.562386,0 0,46.562386 0,104 C0,161.437614 46.562386,208 104,208 C161.437614,208 208,161.437614 208,104 C208,46.562386 161.437614,0 104,0 L104,0 Z M104,128 C90.745166,128 80,117.254834 80,104 C80,90.745166 90.745166,80 104,80 C117.254834,80 128,90.745166 128,104 C128,117.254834 117.254834,128 104,128 Z"
                                      id="Shape"></path>
                            </g>
                            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="235"></circle>
                            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="215"></circle>
                            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="195"></circle>
                            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="175"></circle>
                            <circle id="Oval" stroke="#979797" cx="248" cy="248" r="155"></circle>
                        </g>
                    </g>
                </svg>
            </div>
            <div class="col-12 col-md-8 ps-5">


                <div {{ stimulus_controller('') }}></div>
                <h2 class="mb-4">10 songs (30 minutes of 60 still available)</h2>

                {% for track in tracks %}

                    <div class="song-list" {{ stimulus_controller('song-controls', {
                        infoUrl: path('api_songs_get_one', { id: loop.index })
                    }) }}>
                        <div class="d-flex mb-3">
                            <a href="#" {{ stimulus_action('song-controls', 'play') }}>
                                <i class="fas fa-play me-3"></i>
                            </a>
                            <span class="song-details">{{ track.song }} - {{ track.artist }}</span>
                            <a href="#">
                                <i class="fas fa-bars mx-3"></i>
                            </a>
                            <a href="#">
                                <i class="fas fa-times"></i>
                            </a>
                        </div>
                    </div>

                {% endfor %}

                <button type="button" class="btn btn-success"><i class="fas fa-plus"></i> Add a song</button>
            </div>
        </div>
    </div>
{% endblock %}